name: Release please

on: pull_request

jobs:
  auto-merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.user.login == 'release-please[bot]'
    steps:
    - name: Enable auto-merge for Release please PRs
      run: gh pr merge --auto --rebase "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
