name: Update API schema

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,10,14,18 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Extract version from current api docs
        id: before
        uses: mikefarah/yq@master
        with:
          cmd: yq '.info.version' 'openapi.yaml'

      - name: Fetch schema
        run: wget -qO openapi.yaml https://hackaton-api.fly.dev/api/v1/docs
    
      - name: Extract version from latest api docs
        id: after
        uses: mikefarah/yq@master
        with:
          cmd: yq '.info.version' 'openapi.yaml'

      - name: Check if schema has changed
        run: echo "::notice title=version::${{ steps.after.outputs.result }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          token: ${{ secrets.UPDATE_SCHEMA_TOKEN }}
          title: 'fix(api-docs): update schema from ${{ steps.before.outputs.result }} to ${{ steps.after.outputs.result }}'
          commit-message: 'fix(api-docs): update schema from ${{ steps.before.outputs.result }} to ${{ steps.after.outputs.result }}'
          body: 'Fetch and format the latest API schema.'
          branch: update-schema--${{ github.ref_name }}
          delete-branch: true
          labels: bot,📙 openapi

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.UPDATE_SCHEMA_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
